// Project configuration
// Rename this from config.example.js to config.js and fill it out in order to use it during development.

// Remember, doing production a config.js will be auto-generated by ow-plugin and this one is ignored. (as specified by the .env files)
// Also remember that config.js should never be committed and should be gitignored.

window.config = {
  // URL to the service registry.
  "service_registry": "https://<FILL ME>",
  // URL to the dashboard itself
  "base_url": "/dashboard/",
  // URL to wp-authenticator
  "auth_url": "/wp-authenticator/",
  // Relative path to the root of wordpress
  "wp_dir": "../",

  // domain which the dashboard will be generated for. Leave blank for javascript to pull this from the current url. (NotPass credentials required)
  "target_domain": null,
  // If the site auto-redirects to https, you might have to set this to true
  "force_ssl": false,
  // Set this to true to show the sales panel.
  "doesSales": true,
  // Set this to true to show the activities feed.
  "activityFeed": true,

  // The following fields are only meant to be used during development, and should be ommited during production.

  // Thou-Shalt-Not-Pass credentials - Authentication is required for some development features.
  "dev_api_username": null,
  "dev_api_key": null,
  // Set this to true to bypass authentication with wp-authenticator. (NotPass credentials required)
  "bypass_login": false,
  // If you want to use a custom service-registry enviorment, set this. (NotPass credentials required)
  "service_registry_env": null,

  // The following fields are deprecated fields that don't need to be provided anymore.

  // URL to reporting service. This is a legacy field that will only be used when service_registry isn't provided.
  // "reporting_server": "https://<FILL ME>/v2",
  // This is the same as providing dev_api_key and setting bypass_login to true.
  // "login_token": "<Leave blank or insert thou-shalt-not-pass api-key>",
}
